# render.yaml — Worker + Persistent Disk (PAID)

services:
  - type: worker
    name: say-quiz-bot
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py

    # Усі значення задані тут, але BOT_TOKEN обов'язково заміни в Dashboard після створення
    envVars:
      - key: BOT_TOKEN
        value: "CHANGE_ME"
      - key: LANG
        value: "uk"
      - key: ENABLE_MEDIA
        value: "1"
      - key: OWNER_IDS
        value: "5798500887"
      - key: TESTS_ROOT
        value: "/data/tests"           # тести/медіа зберігаються на диску
      - key: DB_URL
        value: "sqlite:////data/stats.db"   # база на диску
      - key: LOG_LEVEL
        value: "INFO"
      # - key: LOG_FILE
      #   value: "/data/logs/bot.log"  # опційно: лог-файл на диску

    # Персистентний диск (платний). Розмір можеш змінити.
    disk:
      name: data
      mountPath: /data
      sizeGB: 5
