# render.yaml — інфра для Render.com (безкоштовний план)
# Створює Background Worker і безкоштовний диск /data.

services:
  - type: worker
    name: say-quiz-bot
    env: python
    plan: free          # <<< ДОДАНО — вибір безкоштовного плану
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py

    envVars:
      - key: BOT_TOKEN
        value: "CHANGE_ME"
      - key: LANG
        value: "uk"
      - key: ENABLE_MEDIA
        value: "1"
      - key: OWNER_IDS
        value: "5798500887"
      - key: TESTS_ROOT
        value: "/data/tests"
      - key: DB_URL
        value: "sqlite:////data/stats.db"
      - key: LOG_LEVEL
        value: "INFO"

    disk:
      name: data
      mountPath: /data
      sizeGB: 1
      plan: free        # <<< ДОДАНО — диск також безкоштовний
