# render.yaml — інфра для Render.com
# Створює Background Worker і підключає персистентний диск /data.

services:
  - type: worker
    name: say-quiz-bot
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py

    # Значення секретів додаси у Render → Environment (UI)
    envVars:
      - key: BOT_TOKEN
        value: "CHANGE_ME"         # тимчасове значення, щоб Render не лаявся
      - key: LANG
        value: "uk"
      - key: ENABLE_MEDIA
        value: "1"
      - key: OWNER_IDS
        value: "5798500887"
      - key: TESTS_ROOT
        value: "/data/tests"
      - key: DB_URL
        value: "sqlite:////data/stats.db"
      - key: LOG_LEVEL
        value: "INFO"
      # - key: LOG_FILE
      #   value: "/data/logs/bot.log"

    disk:
      name: data
      mountPath: /data
      sizeGB: 5
